[package]
name = "remotestylus-ipados"
version = "0.1.0"
edition = "2021"

[dependencies]
libremotestylus = { path = "../../core" }

[target.'cfg(target_os="ios")'.dependencies]
objc = "0.2.7"
objc-foundation = "0.1.1"
objc_id = "0.1.1"