[package]
name = "libremotestylus"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
rmp-serde = "0.15.5"
serde = { version = "1.0.133", features = ["derive"] }
clap = { version = "3.0.1", features = ["derive"] }
laminar = "0.5.0"
crossbeam-channel = "0.5.2"